- name : Mysql
  hosts: all
  tasks: 
    - name: install mysql server
      ansible.builtin.dnf:
        name: Mysql-server
        state: latest

    - name: start mysql
      ansible.builtin.systemd_service:
         name: mysql
         state: started
         enabled: yes
         
    - name: setup password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1 
      