- name : MySQL Setup
  hosts: all
  become: yes
  tasks: 
    - name: install MYSQL server
      ansible.builtin.dnf:
        name: mysql-server
        state: latest

    - name: MySQL service
      ansible.builtin.service:
        name: MySQL
        state: restarted
        enabled: yes

    - name: setup MySQL password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1 
      